### ISSUE TITLE
What is the last release version to use ?

### ISSUE THREAD

**Issue by MobiliteDev** [davidmartos96/sqflite_sqlcipher#10]
Hi,

Thank you for your great job !
In your Readme, you tell what we have to use the the commit 8f7a3899d3bd80090a8be2f68a0f285e753401e9 to override **sqflite** dependency.

But, you're always updating your project, that's good, but, do you consider that we can use aea20e46002863a44327b805629b0a2c2b8b2d89 commit in production to have the latest sqflite version ?

Or do we have to wait for readme update ?

**Comment by davidmartos96** [comment]
I would stick with the version in the readme, that is what I have been using without issues in my own project for quite a while now. The update in the repo from last week was just to keep with sqflite latest master (1.2.1-dev.3 at that point), and solve some merge conflicts.
