### ISSUE TITLE
Pod incompatibility

### ISSUE THREAD

**Issue by quangduy-luong** [davidmartos96/sqflite_sqlcipher#100]
We've been using sqflite_sqlcipher for a long time now, but starting last week, we can no longer get the app to compile because pod install always fails.

We used version 2.2.1 with dependency override, and this is the output from Cocoapods:

```
CocoaPods could not find compatible versions for pod "SQLCipher":
  In Podfile:
    sqflite (from `.symlinks/plugins/sqflite/ios`) was resolved to 0.0.2, which depends on
      FMDB/SQLCipher (>= 2.7.5) was resolved to 2.7.11, which depends on
        SQLCipher (~> 4.0)

    sqflite (from `.symlinks/plugins/sqflite/ios`) was resolved to 0.0.2, which depends on
      SQLCipher (~> 4.5.0)

    sqflite_sqlcipher (from `.symlinks/plugins/sqflite_sqlcipher/ios`) was resolved to 0.0.1, which depends on
      SQLCipher (= 4.5.4)
```

After trying to update to 3.1.0+1 and removing the dependency override, this is what we get instead:

```
CocoaPods could not find compatible versions for pod "SQLCipher":
  In Podfile:
    sqflite_sqlcipher (from `.symlinks/plugins/sqflite_sqlcipher/ios`) was resolved to 0.0.1, which depends on
      FMDB/SQLCipher (~> 2.7.5) was resolved to 2.7.11, which depends on
        SQLCipher (~> 4.0)

    sqflite_sqlcipher (from `.symlinks/plugins/sqflite_sqlcipher/ios`) was resolved to 0.0.1, which depends on
      SQLCipher (= 4.5.7)
```

Any idea how to resolve this?

**Comment by davidmartos96** [comment]
Could you post your pubspec.yaml file? I believe it could be a transitive/direct dependency issue which is using SQLCipher.

**Comment by jozefvodicka** [comment]
Here is the pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite_sqlcipher: ^2.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.11
  built_value_generator: ^8.8.1
  flutter_launcher_icons: <1.0.0
  patrol: ^3.10.0
  lints: ^4.0.0
  test: ^1.25.0
  test_api: any

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

**Comment by quangduy-luong** [comment]
Hello, in the end, it turns out that it wasn't the issue with this plugin but a related issue in qr_mobile_vision. Fixing the problem for their plugin also resolved this one.
