### ISSUE TITLE
Plans to update to the latest version

### ISSUE THREAD

**Issue by Michels10** [davidmartos96/sqflite_sqlcipher#101]
Hi,

I was wondering if there were any plans for this repository to be updated to the latest version of [sqlflite].(https://github.com/tekartik/sqflite). 

Thanks!

**Comment by davidmartos96** [comment]
The repo started as a fork, but nowadays it uses sqflite_common under the hood, same as sqflite.
You can also check out this post: https://github.com/davidmartos96/sqflite_sqlcipher/issues/73#issuecomment-2045441193
