### ISSUE TITLE
Error (Xcode): Multiple commands produce

### ISSUE THREAD

**Issue by Shahid-raheem** [davidmartos96/sqflite_sqlcipher#102]
Error (Xcode): Multiple commands produce
'/Users/shahid/Library/Developer/Xcode/DerivedData/Runner-cuqsoeatlklhihfgyafcaczozlqd/Build/Intermediates.noindex/ArchiveIntermediates/Runner/Intermediat
eBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'

**Comment by davidmartos96** [comment]
Duplicate of https://github.com/davidmartos96/sqflite_sqlcipher/issues/95
