### ISSUE TITLE
Cannot run APK in release mode

### ISSUE THREAD

**Issue by jlcool** [davidmartos96/sqflite_sqlcipher#13]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G87,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)

• No issues found!

can debug can not release

create new flutter project,add code to pubspec.yaml

``` dart
sqflite:
    git:
      url:  https://github.com/davidmartos96/sqflite_sqlcipher
      path: sqflite
```

then flutter build apk
flutter install
Cannot run app

**Comment by davidmartos96** [comment]
That is because it's not published, I have just been messing around a bit with it in a different branch.
What happens if you add `ref: master` to the got dependency?

**Comment by jlcool** [comment]
add `ref: master` or `ref: 50a4ac06b323e1ce3d0cd055125a6f4a7454f2d5`
Still crash，Do you have this problem

**Comment by davidmartos96** [comment]
No, I don't. Are you using ProGuard? That could be why it's only failing on release mode.
In the README there is a setting that you would need to add if that is the case.

**Comment by davidmartos96** [comment]
Also, could you share the crash logs?

**Comment by jlcool** [comment]
https://github.com/jlcool/flutter_sqflite_crash  I didn't add any code, just modified pubspec.yaml

**Comment by jlcool** [comment]
How to view logs

**Comment by davidmartos96** [comment]
If you got your phone connected, you could do ` flutter run --release`. It will build the APK for you.

**Comment by jlcool** [comment]
`flutter run --release` can run  no crash

**Comment by jlcool** [comment]
But when I execute 
```
flutter clean 
fluent build apk
flutter install
```
then crash

**Comment by davidmartos96** [comment]
Alright, I will try your repo, in the meantime you could try using a different ref commit, for example: 8f7a3899d3bd80090a8be2f68a0f285e753401e9

**Comment by jlcool** [comment]
There's still a problem

**Comment by jlcool** [comment]
https://github.com/jlcool/flutter_sqflite_crash，No code was added, only pubspec.yaml was modified

**Comment by davidmartos96** [comment]
I was able to reproduce and these are the 2 solutions. It looks like shrinking is being enabled by default.
1. Configure your build.gradle in the android/app folder:
```
release {
            signingConfig signingConfigs.release
            
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            debuggable false

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
```
Create a new file in the android/app folder `proguard-rules.pro`
```
#SqlCipher
-keep class net.sqlcipher.** { *; } 
-keep class net.sqlcipher.database.* { *; }
```

1. If you don't want to use shrinking at all, explicitly add these options to the build.gradle in the app folder:
```
minifyEnabled false
shrinkResources false
```

**Comment by davidmartos96** [comment]
Also, I found this, which I think is related:
https://github.com/flutter/flutter/issues/48015

**Comment by davidmartos96** [comment]
@jlcool Any updates? Or can I close this? I've updated the README regarding this small issue.

**Comment by jlcool** [comment]
thank you，is ok

**Comment by alanmfb** [comment]
> I was able to reproduce and these are the 2 solutions. It looks like shrinking is being enabled by default.
> 
> 1. Configure your build.gradle in the android/app folder:
> 
> ```
> release {
>             
>             minifyEnabled true
> 
>             // Enables resource shrinking, which is performed by the
>             // Android Gradle plugin.
>             shrinkResources true
> 
>             debuggable false
> 
>             // Includes the default ProGuard rules files that are packaged with
>             // the Android Gradle plugin. To learn more, go to the section about
>             // R8 configuration files.
>             proguardFiles getDefaultProguardFile(
>                     'proguard-android-optimize.txt'),
>                     'proguard-rules.pro'
>         }
> ```
> 
> Create a new file in the android/app folder `proguard-rules.pro`
> 
> ```
> #SqlCipher
> -keep class net.sqlcipher.** { *; } 
> -keep class net.sqlcipher.database.* { *; }
> ```
> 
> 1. If you don't want to use shrinking at all, explicitly add these options to the build.gradle in the app folder:
> 
> ```
> minifyEnabled false
> shrinkResources false
> ```

Apparently it worked for me!
