### ISSUE TITLE
Encryption enabled message for Android

### ISSUE THREAD

**Issue by bremington** [davidmartos96/sqflite_sqlcipher#18]
David, I have your code working very well on both iOS and Android. When I initialize my iOS devices it logs Encryption enabled. I have the statement for proguard on Android and everything seems to work fine, except I dont see the Encryption enabled log message. Does this mean the encryption is not working or is there something else needed to display this confirmation on Android?

Thank you!

**Comment by davidmartos96** [comment]
Actually, that message is only printed on iOS. I will remove it to avoid confusion.
Thanks for pointing it out!

**Comment by davidmartos96** [comment]
Closed by af9c519
