### ISSUE TITLE
Hi David

### ISSUE THREAD

**Issue by misici234** [davidmartos96/sqflite_sqlcipher#22]
Your example project on https://pub.dev/packages/sqflite_sqlcipher/example is not complete. You provided us only example/lib/main.dart file but no other files which are imported into this one. Please added the missing files and fully expose your example project. Thanks.
Regards, Boris Misic

**Comment by davidmartos96** [comment]
Hi! That is how pub.dev works. It only shows the main file.
If you want to look at the whole example I encourage you to clone the repository and take a look at teh whole example.
In any case, the example project is more like a test suite than an example. You may want to look up how to use the sqflite library first. This is the same API, only that the database is encrypted and there is an optional parameter when opening/creating the database.

**Comment by misici234** [comment]
Where is your repository with this example? I tried to search it and couldn't find it there.

**Comment by davidmartos96** [comment]
It's under the sqflite directory
https://github.com/davidmartos96/sqflite_sqlcipher/tree/master/sqflite/example
