### ISSUE TITLE
Can sqflite_sqlcipher  encrypt the database created by sqflite

### ISSUE THREAD

**Issue by yingqiang006** [davidmartos96/sqflite_sqlcipher#23]

**Comment by davidmartos96** [comment]
Do you mean encrypting an existing database from sqflite?

**Comment by yingqiang006** [comment]
> Do you mean encrypting an existing database from sqflite?

yes。At first, sqlflite was used, but now encryption is needed

**Comment by yingqiang006** [comment]
> Do you mean encrypting an existing database from sqflite?

Can it be satisfied? What do I need to do?

**Comment by davidmartos96** [comment]
@yingqiang006  Yes, you can do that. You can refer to this issue https://github.com/davidmartos96/sqflite_sqlcipher/issues/20

**Comment by yingqiang006** [comment]
> @yingqiang006 Yes, you can do that. You can refer to this issue #20

Thank you. I'll take a look
