### ISSUE TITLE
What is the algorithm used to encrypt the database?

### ISSUE THREAD

**Issue by GP4cK** [davidmartos96/sqflite_sqlcipher#29]
Is it correct to say that it's using 256-bit AES in CBC mode?
From https://www.zetetic.net/sqlcipher/design/

**Comment by davidmartos96** [comment]
@GP4cK  I'm not really the right person to answer that.
Since that is a quote from the official page, why wouldn't it be correct? 😅
If you need more details you could ask in the official forum

**Comment by GP4cK** [comment]
Ok I tried to look at the source code but didn't see anything. I just wanted confirmation. Thanks

**Comment by davidmartos96** [comment]
@GP4cK Note that this repository is just a wrapper to the SQLCipher native implentations.
You can find the source code here: https://github.com/sqlcipher/sqlcipher
