### ISSUE TITLE
Error With Ios

### ISSUE THREAD

**Issue by binodlohani** [davidmartos96/sqflite_sqlcipher#3]
Database is created and Encrypted with "DB Browser for SQLite".
Works well in Android .
If Encryption is removed works well in IOS too . 
But Produce Exception in exception_impl.dart in case of Encrypted Database . 
---------------
Encryption is ready.
Unknown error calling sqlite3_step (26: file is not a database) eu
DB Query: BEGIN EXCLUSIVE
Unknown error finalizing or resetting statement (26: file is not a database)
DB Query: BEGIN EXCLUSIVE
---------------------
<img width="962" alt="Untitled" src="https://user-images.githubusercontent.com/47173611/60378583-10186a80-9a44-11e9-94ca-d0c1181dc347.png">

Any Idea on what to do ??
Thanks !!

**Comment by davidmartos96** [comment]
Are you using a database created within the app or one prepopulated?

**Comment by binodlohani** [comment]
> Are you using a database created within the app or one prepopulated?
The Database was not created within the app ..
It was pre-populated and copied to the local directory form Asset.

**Comment by davidmartos96** [comment]
Alright, in the app I am developing I was also having that problem when using a bundled db. When you do writeBytes to copy, are you using the parameter flush with the value true?

**Comment by binodlohani** [comment]
This is what i did to copy file in 
<img width="756" alt="Untitled" src="https://user-images.githubusercontent.com/47173611/60383691-f868d280-9a93-11e9-9980-67050889a4d4.png">

**Comment by davidmartos96** [comment]
Could the database be somewhat corrupted and already copied in the device. Try to temporarily remove the if statement to always copy the database to see it that could be the issue.

**Comment by binodlohani** [comment]
That doesnot make any difference .. 
Note that I have tested after deleting the directory to .. 
and even tested with what you said .

**Comment by binodlohani** [comment]
> Alright, in the app I am developing I was also having that problem when using a bundled db. When you do writeBytes to copy, are you using the parameter flush with the value true?

How did you solve the problem ?? Was the problem same ??

**Comment by davidmartos96** [comment]
The couple of problems I had when opening my database where opening a wrong SqlCipher version and not flushing the write operation

**Comment by davidmartos96** [comment]
You said it works fine one Android? Did you try to use getDatabasesPath() instead of applicationDocumentDirectory?

**Comment by binodlohani** [comment]
> You said it works fine on Android? Did you try to use getDatabasesPath() instead of applicationDocumentDirectory?

yes ! that doesnot makes any difference

**Comment by davidmartos96** [comment]
So in Android works and in iOS doesn't?

**Comment by binodlohani** [comment]
yes It works on android and not in Ios . Could we talk in telegram if it doesnot offend the rule ..

**Comment by davidmartos96** [comment]
@binodlohani Sure, send me your Telegram ID to davidmartos96@gmail.com

**Comment by thuraucsy** [comment]
This bug is happening on iOS, any solution for that?

**Comment by davidmartos96** [comment]
@thuraucsy A configuration may be missing for iOS in the docs. I don't have an iPhone, but my friend does and our app with this SqlCipher works fine on iOS. Could you try adding this to the Podfile in the ios folder?
![image](https://user-images.githubusercontent.com/22084723/65771124-cd942600-e137-11e9-808c-734bdf7ceab5.png)
I would like to update the docs if needed...

**Comment by thuraucsy** [comment]
@davidmartos96  
Thank you very much for the quick reply.
I added SQLCipher as you said in the Podfile but the error still happening. But when I change the version to ~>3.4.2 the error has gone! 

Finally, it works! Thank you. 👍 


```

target 'Runner' do

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }

  pod 'SQLCipher', '~>3.4.2'

  use_frameworks!
end

```

**Comment by davidmartos96** [comment]
@thuraucsy Great, glad it worked! If it's not much to ask, what is your iPhone and iOS version? Also are you using an encrypted db from assets, or is it generated in the app?

**Comment by thuraucsy** [comment]
I'm using iPhone X with iOS 12.4.1. Yes I'm using db from assets like [that](https://github.com/davidmartos96/sqflite_sqlcipher/issues/3#issuecomment-506951275)

**Comment by davidmartos96** [comment]
Alright thanks. I would say it was failing because your iOS version was using SqlCipher 4.x by default and your db is encrypted with version 3.x. They are incompatible. Here is some information [Upgrading to SQLCipher 4](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283). Note that the Android side will use SqlCipher 4, as it will migrate from 3 to 4 if needed. Not in iOS though. 

To get the version of the sqlcipher you are using:
1. Type `sqlcipher` in your console.
2. Type ` PRAGMA cipher_version;` in the sql command line   (Ctrl+D to exit)

**Comment by thuraucsy** [comment]
Thanks for the detail explanation. I will try to update my db with version 4.

**Comment by FranciscoBeccuti** [comment]
Hi.

I have the same problem.
The application works correctly on Android but not on iOS.
The sqlcipher version of the database is 4.
The pod used is 'SQLCipher', '~> 4.4.0'
I am also using getDatabasesPath ()
Any suggestion?

Thank you

**Comment by davidmartos96** [comment]
@FranciscoBeccuti 
What error are you getting?
Is it a problem with a database from assets, or a fresh database created in the device?

**Comment by FranciscoBeccuti** [comment]
> @FranciscoBeccuti
> What error are you getting?
> Is it a problem with a database from assets, or a fresh database created in the device?

The database works correctly on both Android and iOS but it was not encrypted.
Encrypting it and starting to use sqflite_sqlcipher started this problem.
The database is in Asset and was created using 'db browser for sqlite'.
The error says:

[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=26 "file is not a database" UserInfo={NSLocalizedDescription=file is not a database}) sql 'SELECT * FROM tips WHERE idTipo = 1 AND idIdioma = 1 ORDER BY texto' args []}
#0      SqfliteSqlCipherDatabaseFactoryImpl.wrapDatabaseException (package:sqflite_sqlcipher/src/factory_sql_cipher_impl.dart:44:9)

**Comment by davidmartos96** [comment]
@FranciscoBeccuti    So the same encrypted database from assets works on Android but not on iOS?
What iOS version are you using? 
That error usually happens when opening a SQLCipher 3 database with version 4.X or viceversa or when providing an invalid password.
You can try running the example project on your device and see if the problem is with the repo or with your database.
https://github.com/davidmartos96/sqflite_sqlcipher/tree/master/sqflite/example

**Comment by davidmartos96** [comment]
@FranciscoBeccuti Now that I think about it, most probably you are encrypting you database with SQLCipher 3.x. On Android it will migrate to version 4 automatically, but not on iOS.
In any case I would recommend upgrading to version 4 if that is the case.
You can check what version of SQLCipher you are running on desktop with the sqlcipher CLI (PRAGMA cipher_version)

![image](https://user-images.githubusercontent.com/22084723/94026491-094ce480-fdba-11ea-8191-caecd24f1fd3.png)

**Comment by FranciscoBeccuti** [comment]
> @FranciscoBeccuti So the same encrypted database from assets works on Android but not on iOS?

Yes, same database run OK on Android.

> What iOS version are you using?

Emulator, iphone se 2nd with ios 13.7

> That error usually happens when opening a SQLCipher 3 database with version 4.X or viceversa or when providing an invalid password.
> You can try running the example project on your device and see if the problem is with the repo or with your database.
> https://github.com/davidmartos96/sqflite_sqlcipher/tree/master/sqflite/example

The example run OK, The only error it gives is the conversion from 3 to 4 but it is expected.

I encrypted the database using the 'db browser sqlite 3.12.0', which claims to be using sqlcipher 4.4.0 community based on sqlite 3.31.0

**Comment by davidmartos96** [comment]
@FranciscoBeccuti  That is really strange then. Have you tried uninstalling and installing the app again? Maybe you are opening an outdated assets database.
From your last comment, I'm really clueless on what could be wrong.
As a last check, what versions do you have on your Podfile.lock? If you use any package like cache_network_image you need to make sure to override the sqflite dependency.
You need to have something like below. Sqflite may or may not appear, but if it does, it needs to have the FMDB/SQLCipher dependency.

![image](https://user-images.githubusercontent.com/22084723/94030951-a9a50800-fdbe-11ea-86ee-e410bd18419c.png)

**Comment by FranciscoBeccuti** [comment]
Hi.
Well, I found the problem.
sqflite_sqlcipher is not friends with jaguar_orm
I'm using
jaguar_orm: ^ 2.2.7
jaguar_query_sqflite: ^ 2.2.11
Which work fine with sqflite_sqlcipher under Android but not on iOS.
Any suggestion?

**Comment by FranciscoBeccuti** [comment]
You can reproduce the problem by adding
jaguar_orm: ^ 2.2.7
jaguar_query_sqflite: ^ 2.2.11
in the example of
https://github.com/davidmartos96/sqflite_sqlcipher/tree/master/sqflite/example

**Comment by davidmartos96** [comment]
I'm not experienced with jaguar but I'm pretty sure the issue is that you are not overriding the sqflite dependency on the pubspec.

Take a look at that section:
https://github.com/davidmartos96/sqflite_sqlcipher/blob/master/sqflite/README.md#if-using-sqflite-as-direct-or-transitive-dependency

**Comment by FranciscoBeccuti** [comment]
> I'm not experienced with jaguar but I'm pretty sure the issue is that you are not overriding the sqflite dependency on the pubspec.
> 
> Take a look at that section:
> https://github.com/davidmartos96/sqflite_sqlcipher/blob/master/sqflite/README.md#if-using-sqflite-as-direct-or-transitive-dependency

Yes, that fixed the problem.
Thank you very much for your time!

**Comment by davidmartos96** [comment]
@FranciscoBeccuti Glad you got it working.

**Comment by fauzy6493** [comment]
![Screen Shot 2020-09-25 at 19 32 28](https://user-images.githubusercontent.com/17522833/94268062-ce3be400-ff66-11ea-8efb-7c58bca969b9.png)


Hi @davidmartos96 , I have error when using native code. said **"file is not a database".**
But in dart side running well.

I have double check database path, database password, database name. both same (dart, obj-c).
Also in android running ok..

For SQLCipher version, I try to download db in android, and run PRAGMA cipher_version result is 4.4.0 community. This version also same with my pod file:

`pod 'SQLCipher', '~>4.4.0'`

![Screen Shot 2020-09-25 at 19 41 38](https://user-images.githubusercontent.com/17522833/94268293-270b7c80-ff67-11ea-84ee-5677a40c2fc4.png)


Anything else to check with this error?
Is user version take effect of this error?

**Comment by davidmartos96** [comment]
@fauzy6493   Does it work on Dart side iOS?
"PRAGMA cipher_version" does not return the version of the database, but the version of the SQLCipher "toolchain" that is being used on that device. Running cipher_version on the phone is expected to return version 4.x because that is what is being specified on the Podfile.
I don't have much experience with native iOS development. I would encourage you to check out the ios implementation on this repo to see if you may be missing something when opening the database.

Also, make sure that you followed the instructions below in case that is the issue:
https://github.com/davidmartos96/sqflite_sqlcipher/blob/master/sqflite/README.md#if-using-sqflite-as-direct-or-transitive-dependency

It would be very strange that it opens fine with the native implementation of the plugin but not with your custom code. Probably something is missing.

**Comment by fauzy6493** [comment]
> @fauzy6493 Does it work on Dart side iOS?

Yes it work well in Dart side iOS. But native side didn't work.

I also try using dependency_overrides in my pubspec.yaml but noting happen.
`
dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override
`

**Comment by davidmartos96** [comment]
@fauzy6493 I don't see why it wouldn't work on native side then. Not sure how to help you there.
That is new native code that is not communicating with this package. 
Maybe you can try get some help on the SQLCipher forum / Github

**Comment by fauzy6493** [comment]
![Screen Shot 2020-09-30 at 11 31 31](https://user-images.githubusercontent.com/17522833/94643516-3268fa00-0311-11eb-98b5-23e7bf4f6f16.png)

Hi, I suspect conflict between SQLCipher and firebase google. Because before I adding firebase into my project, SQLCipher is working fine.

But now issue is solved already. By adding linker flag in Xcode Linker Flag as shown in attached screenshot above.
Hope this help every one who got same issue with me.

Thank you for your kind support @davidmartos96

**Comment by Keshavsaini137** [comment]
Having the same issue solution
