### ISSUE TITLE
I use it on the macOS platform, and there are a lot of warning messages when compiling.

### ISSUE THREAD

**Issue by HeebeLee** [davidmartos96/sqflite_sqlcipher#36]
sqflite_sqlcipher: ^2.0.0

This may be a problem with sqlcipher. Quite a lot, I just copied part of it.

Launching lib/main.dart on macOS in debug mode...
/Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:33879:25: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
          szBufNeeded = MAX(e2,0)+(i64)precision+(i64)width+15;
                        ^
In module 'Darwin' imported from /Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:1088:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/param.h:218:9: note: expanding this definition of 'MAX'
#define MAX(a, b) (((a)>(b))?(a):(b))
        ^
/Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:14318:10: note: other definition of 'MAX'
# define MAX(A,B) ((A)>(B)?(A):(B))
         ^
/Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:37974:14: warning: implicit conversion loses integer precision: 'sqlite3_int64' (aka 'long long') to 'VList' (aka 'int') [-Wshorten-64-to-32]
    pIn[0] = nAlloc;
           ~ ^~~~~~
/Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:40084:14: warning: implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    do{ rc = osWrite(fd, "S", 1); }while( rc<0 && errno==EINTR );
           ~ ^~~~~~~~~~~~~~~~~~~
/Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:39128:21: note: expanded from macro 'osWrite'
#define osWrite     ((ssize_t(*)(int,const void*,size_t))aSyscall[11].pCurrent)
                    ^
/Users/xx/../flutter/macos/Pods/SQLCipher/sqlite3.c:41829:42: warning: implicit conversion loses integer precision: 'unsigned long long' to 'int' [-Wshorten-64-to-32]
        int sharedLockByte = SHARED_FIRST+pInode->sharedByte;
            ~~~~~~~~~~~~~~   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~

**Comment by davidmartos96** [comment]
Do you get a crash at the end, or are those "just" warnings? The warnings are generated by the official SqlCipher native library which it is outside this repository. 
Unfortunately one has to live with those warnings..

**Comment by HeebeLee** [comment]
These are just warnings and did not crash my app, but there are a lot of
warnings, with more than 120 repeated warnings.  If there is no way to
solve it, it can only be so.

**Comment by davidmartos96** [comment]
@HeebeLee Yes, as far as I know, we cannot do anything about it here. I don't know if there are ways to ignore warnings for certain libraries when compiling.
