### ISSUE TITLE
COLLATE LOCALIZED not working

### ISSUE THREAD

**Issue by Aksoyhlc** [davidmartos96/sqflite_sqlcipher#38]
Dart Unhandled Exception: DatabaseException(no such collation sequence: LOCALIZED: , while compiling: SELECT * FROM menu WHERE status=1 ORDER BY title COLLATE LOCALIZED ASC )}, stack trace: #0      SqfliteSqlCipherDatabaseFactoryImpl.wrapDatabaseException (package:sqflite_sqlcipher/src/factory_sql_cipher_impl.dart:44:9)

**Comment by davidmartos96** [comment]
@Aksoyhlc Hello! I wasn't aware lf this, but it looks like it is a limitation of the native SqlCipher binary that it's used by this package. Here you have more information. 
Unfortunately I cannot do anything about it, this is a wrapper of said official native library.

https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515
