### ISSUE TITLE
deprecated warnings...

### ISSUE THREAD

**Issue by Abhijit-Revamp** [davidmartos96/sqflite_sqlcipher#40]
when I create a release build for APK, getting following warning:

/.pub-cache/hosted/pub.dartlang.org/sqflite_sqlcipher-2.0.0/android/src/main/java/com/davidmartos96/sqflite_sqlcipher/SqfliteSqlCipherPlugin.java:37: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;  

Similar warnings are there while building for iOS

**Comment by davidmartos96** [comment]
@Abhijit-Revamp You can ignore the warnings. The plugin native side is up to date but the deprecated way of doing things is still there for backwards compatibility
