### ISSUE TITLE
Deprecation warning while building flutter APK

### ISSUE THREAD

**Issue by Adarshkl** [davidmartos96/sqflite_sqlcipher#46]
Getting the following warning in Android Studio console while building APK.

`
\flutter SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite_sqlcipher-2.0.0\android\src\main\java\com\davidmartos96\sqflite_sqlcipher\SqfliteSqlCipherPlugin.java:37: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^

1 warning
Running Gradle task 'assembleRelease'... 
`

**Comment by davidmartos96** [comment]
That's because the plugin is using the new and old way of registering with the native platform at the same time. Once it's completely removed from the Flutter framework I'll remove it as well.

**Comment by davidmartos96** [comment]
https://github.com/davidmartos96/sqflite_sqlcipher/issues/40#issuecomment-825920950
