### ISSUE TITLE
Warning: deprecated api

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [davidmartos96/sqflite_sqlcipher#49]
Hello and thank you for your great job here. Recently when I'm trying to use the package I get this warning. App works fine but it shows the warning when compiling.

D:\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite_sqlcipher-2.0.0\android\src\main\java\com\davidmartos96\sqflite_sqlcipher\SqfliteSqlCipherPlugin.java:37: warning: [dep
recation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
1 warning

**Comment by davidmartos96** [comment]
That's to be expected, but if you are on a new version of Flutter it doesn't use the deprecated class.
Take a look here: https://github.com/davidmartos96/sqflite_sqlcipher/issues/46
It will be removed once Flutter SDK removes it as well.

**Comment by MojtabaTavakkoli** [comment]
Thanks for your fast response. I checked the closed issues but likely I didn't see that sorry.
