### ISSUE TITLE
App crashes when building an app or using an app bundle

### ISSUE THREAD

**Issue by yoavrofe** [davidmartos96/sqflite_sqlcipher#5]
When installing using an app bundle the app crashes. 
Steps to reproduce: 

* `flutter build apk`
`flutter install`

* or : 

`$ flutter build appbundle --target-platform android-arm,android-arm64
`
`$java -jar./ bundletool-all-0.10.3.jar build-apks --bundle=./app-release.aab --output=./my_app.apks`
`$ java -jar ./bundletool-all-0.10.3.jar install-apks --apks=./my_app.apks`

Errors returned: [error.log](https://github.com/davidmartos96/sqflite_sqlcipher/files/3641229/error.log)

**Comment by davidmartos96** [comment]
This is what I'm doing when building an app I have in production using sqlcipher.

```
flutter clean && flutter build appbundle --target-platform android-arm,android-arm64
```
I've never experienced your issue. Do you know if it happens in every device?

**Comment by davidmartos96** [comment]
@yoavrofe I think it has to do with ProGuard.

https://github.com/sqlcipher/android-database-sqlcipher/issues/442
https://github.com/commonsguy/cwac-saferoom/issues/22

**Comment by yoavrofe** [comment]
Thanks! It's working now. 
Do you think there's a way to include it in the plugin itself? It still happens to me with the example app (although pro guard isn't configured there at all), and I had a production app crashing due to this problem.

**Comment by davidmartos96** [comment]
Oh, do you mean that it crashes with the basic Flutter counter app? I may update the docs regarding this. 
DId you solve it adding the ProGuard rules, or removing some configuration somewhere?
Thanks for spotting! :)

**Comment by yoavrofe** [comment]
It crashes the example app on this repository when  running the above commends (I tried using `flutter clean` too).
I solved it by adding the following lines to the proguard-rules.pro files on my production app:
```
-keep class net.sqlcipher.** { *; }
-keep class net.sqlcipher.database.* { *; }
```

For running it on the example app I enabled proguard and added the rules.

**Comment by davidmartos96** [comment]
Alright, thanks! I will take a look

**Comment by davidmartos96** [comment]
@yoavrofe I'm not able to reproduce the issue in the example folder.

```
flutter build apk
flutter run --use-application-binary build/app/outputs/apk/release/app-release.apk
```
The app opens fine for me.

**Comment by yoavrofe** [comment]
I still get the same error. I'll try to investigate this further.

**Comment by krtliv** [comment]
any news? still crashes in production even if i disable pro-guard or add rules

**Comment by davidmartos96** [comment]
@krtliv Is it the same crash as @yoavrofe had? The app I have running in production is working fine with Sqlcipher. It doesn't use pro guard though. If you have the stack trace of the crash please share it.
I understand that your app works fine in debug. It just crashes in production right?

**Comment by krtliv** [comment]
> @krtliv Is it the same crash as @yoavrofe had? The app I have running in production is working fine with Sqlcipher. It doesn't use pro guard though. If you have the stack trace of the crash please share it.
> I understand that your app works fine in debug. It just crashes in production right?

hello, yes it crashes only when i build apk for release, on debug it runs fine, i removed proguard but done a flutter clean and builded again, but still crashes, i will get the logs now

**Comment by krtliv** [comment]
ok, fixed with disabling also minify

```
           shrinkResources false
           minifyEnabled false
```

**Comment by davidmartos96** [comment]
@krtliv Interesting. 
I think `minifyEnabled false` disables ProGuard.
You can try reverting it back to true and use these rules: https://stackoverflow.com/questions/42555125/app-crashes-on-setting-minifyenabled-to-true

**Comment by krtliv** [comment]
> @krtliv Interesting.
> I think `minifyEnabled false` disables ProGuard.
> You can try reverting it back to true and use these rules: https://stackoverflow.com/a/42555193/5617722

you are right for the minify, i thought by turning proguard off im ok, but i guess minify true enables proguard, thanks
