### ISSUE TITLE
StateError - Bad state: No element

### ISSUE THREAD

**Issue by peterhijma** [davidmartos96/sqflite_sqlcipher#53]
I have some code where I want to wait for a database to open, before closing it. In this case this is happening when starting the app and the user is not authenticated.

```dart
await doWhenOpened((_) => attachedDatabase.close());
```

But since some time this results in an error:

```
StateError
Bad state: No element

Crashed in non-app: list.dart in ListMixin.single
encrypted_moor.dart in _SqfliteVersionDelegate.schemaVersion at line 89 within encrypted_moor
Called from: <asynchronous suspension>
engines.dart in DelegatedDatabase._runMigrations at line 307 within moor
Called from: <asynchronous suspension>
engines.dart in DelegatedDatabase.ensureOpen.<fn> at line 289 within moor
```

Somehow, `result.single` throws the `StateError` because result is empty, inside:

```dart
@override
  Future<int> get schemaVersion async {
    final result = await _db.rawQuery('PRAGMA user_version;');
    return result.single.values.first as int;
  }
```

I'm not sure yet how and why. (And if it's my own fault).

Any idea what I can do to prevent this error?

**Comment by davidmartos96** [comment]
> @davidmartos96 I'll try to reproduce later this week. So far only saw this error/exception come into Sentry from production... :)

Did you end up figuring out your issue?

**Comment by peterhijma** [comment]
> > @davidmartos96 I'll try to reproduce later this week. So far only saw this error/exception come into Sentry from production... :)
> 
> Did you end up figuring out your issue?

I’ve not seen the error since! So for I’ll close it. If I have updates in the future I’ll let you know.
