### ISSUE TITLE
App Crashed in Release Mode

### ISSUE THREAD

**Issue by PrabavathiKalidoss** [davidmartos96/sqflite_sqlcipher#55]
App Crashed in Release Mode.How can i rectify this issue.If Anyone facing this?

**Comment by davidmartos96** [comment]
Hello, it's likely that you skipped the configuration for release mode. There I information about it in the README.
Let me know if you still encounter any issues with that.

**Comment by PrabavathiKalidoss** [comment]
Thank You..Now its Working
