### ISSUE TITLE
DatabaseException(error code 8: attempt to write a readonly database) 

### ISSUE THREAD

**Issue by PrabavathiKalidoss** [davidmartos96/sqflite_sqlcipher#57]
DatabaseException(error code 8: attempt to write a readonly database) sql 'INSERT INTO table name ?

  _database = await openDatabase(_databaseName,
          password: _databaseName,
          readOnly: false,
          version: 1, // TODO: Change the version method dynamically
          onConfigure: onConfigure,
          onCreate: onCreate,
          onOpen: onOpen,
          onUpgrade: onUpgrade
      );

Already read only database is false. but why this error?

**Comment by davidmartos96** [comment]
What's the value of _databaseName?

**Comment by PrabavathiKalidoss** [comment]
Ex:praba.db

**Comment by davidmartos96** [comment]
It's possible that the colon (:) is not valid as a file path. Have you tried using something like "myDatabase.db" for the first argument?

**Comment by PrabavathiKalidoss** [comment]
I am not using the colon.I am just show for an example 

the name of db is praba.db

**Comment by davidmartos96** [comment]
Could you share the rest of the code?

**Comment by PrabavathiKalidoss** [comment]
Works well now..I don't know what the problem is

**Comment by PrabavathiKalidoss** [comment]
<img width="1440" alt="Screenshot 2022-01-31 at 5 52 30 PM" src="https://user-images.githubusercontent.com/67138992/151793162-f105470c-9f44-4b9d-8bf2-63cb8c969319.png">


Show this error sometimes. Will you please help me to solve it?

**Comment by davidmartos96** [comment]
@PrabavathiKalidoss  Without a reproducible sample I wouldn't be able to help you. Could you try creating a repo with a demo that produces the same error?
