### ISSUE TITLE
Android 12 release build unable to open database

### ISSUE THREAD

**Issue by surajprasad57** [davidmartos96/sqflite_sqlcipher#59]
In android 12 , release build fails to open database, however if we use latest version of sqlite package there is no such issue. Please upgrade your package to give support for android 12

**Comment by davidmartos96** [comment]
@surajprasad57 You can try using version 2.1.1, where I updated the Android build version, but I'd say the issue you are having is related to the proguard configuration.
Please check the README, for the configuration needed on Android in release mode.

**Comment by surajprasad57** [comment]
Thanks for the quick response. I will update the version to 2.1.1 and also update the proguard file and will update in this thread if everything works fine

**Comment by davidmartos96** [comment]
@surajprasad57 Were you able to get it working?

**Comment by davidmartos96** [comment]
Closing. The example folder in the repository runs and builds with the latest Flutter 3.0.
Let me know if you encounter any issue.
