### ISSUE TITLE
Sqflite update to lastest version

### ISSUE THREAD

**Issue by StigUK** [davidmartos96/sqflite_sqlcipher#66]
Hi. I currently see that the version of [sqflite](https://pub.dev/packages/sqflite) on the [fmdb_override](https://github.com/davidmartos96/sqflite_sqlcipher/tree/fmdb_override) branch is based on sqflite 2.0.0+3. However, this version was released 18 months ago. Since then, many interesting optimizations have been added to sqflite. Will sqflite be updated to the latest version?

**Comment by davidmartos96** [comment]
@StigUK I've updated the branch to be on pair with sqflite `2.0.3+1`.
Thanks for the heads up!
