### ISSUE TITLE
example does not run on iOS

### ISSUE THREAD

**Issue by hellowtisch** [davidmartos96/sqflite_sqlcipher#7]
Hi David,

the example works like a charm on android, however on iOS, After setting the development team the app is deployed to the simulator, however only a white screen is displayed and XCode shows the following errors:
019-11-21 13:43:22.394147+0100 Runner[36624:4158561] flutter: Observatory listening on http://127.0.0.1:54086/hKfP71xnapo=/
2019-11-21 13:43:22.836631+0100 Runner[36624:4153173] -[AppDelegate applicationDidBecomeActive:]: unrecognized selector sent to instance 0x6000003684c0
2019-11-21 13:43:22.843202+0100 Runner[36624:4153173] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate applicationDidBecomeActive:]: unrecognized selector sent to instance 0x6000003684c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e3e302e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010e250b20 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e403f94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x0000000116909f39 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x000000010e3e7b56 ___forwarding___ + 838
	5   CoreFoundation                      0x000000010e3e9f38 _CF_forwarding_prep_0 + 120
	6   Runner                              0x000000010b4c4769 -[AppDelegate applicationDidBecomeActive:] + 89
	7   UIKitCore                           0x00000001168d143d -[UIApplication _stopDeactivatingForReason:] + 1028
	8   UIKitCore                           0x0000000116010976 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 436
	9   UIKitCore                           0x0000000116010d08 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 818
	10  UIKitCore                           0x000000011601059d -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	11  UIKitCore                           0x0000000116014bcb __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 178
	12  UIKitCore                           0x000000011642369b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 865
	13  UIKitCore                           0x000000011651c51f _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	14  UIKitCore                           0x00000001160148e6 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 153
	15  UIKitCore                           0x000000011651c422 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 84
	16  UIKitCore                           0x0000000116014754 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 381
	17  UIKitCore                           0x0000000115e6b123 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 657
	18  UIKitCore                           0x0000000115e69ca8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
	19  UIKitCore                           0x0000000115e6ae4d -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 210
	20  UIKitCore                           0x000000011644567e -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 504
	21  FrontBoardServices                  0x000000011410ecc7 -[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:] + 565
	22  FrontBoardServices                  0x0000000114134a5f __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke_2 + 123
	23  FrontBoardServices                  0x0000000114118d05 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	24  FrontBoardServices                  0x000000011413499c __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke + 196
	25  libdispatch.dylib                   0x0000000111254d48 _dispatch_client_callout + 8
	26  libdispatch.dylib                   0x0000000111257cb9 _dispatch_block_invoke_direct + 300
	27  FrontBoardServices                  0x000000011415a43e __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	28  FrontBoardServices                  0x000000011415a12c -[FBSSerialQueue _queue_performNextIfPossible] + 441
	29  FrontBoardServices                  0x000000011415a63b -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	30  CoreFoundation                      0x000000010e346221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	31  CoreFoundation                      0x000000010e34614c __CFRunLoopDoSource0 + 76
	32  CoreFoundation                      0x000000010e345924 __CFRunLoopDoSources0 + 180
	33  CoreFoundation                      0x000000010e34062f __CFRunLoopRun + 1263
	34  CoreFoundation                      0x000000010e33fe16 CFRunLoopRunSpecific + 438
	35  GraphicsServices                    0x0000000113494bb0 GSEventRunModal + 65
	36  UIKitCore                           0x00000001168dbb48 UIApplicationMain + 1621
	37  Runner                              0x000000010b4c4971 main + 97
	38  libdyld.dylib                       0x00000001112dcc25 start + 1
	39  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Printing description of argv:
(char **) argv = 0x00007ffee473adc0
Printing description of argv:
(char **) argv = 0x00007ffee473adc0
Printing description of *(argv):
(char *) *argv = 0x00007ffee473b0d0 "/Users/marcel/Library/Developer/CoreSimulator/Devices/DCDAF123-29AC-473F-85AD-42F51D8D5B3D/data/Containers/Bundle/Application/7F0EDE4A-08D7-4620-94D5-B5B4B626BBD0/Runner.app/Runner"

See screenshot attached.
<img width="876" alt="Screenshot" src="https://user-images.githubusercontent.com/5956873/69346602-5bd9e380-0c73-11ea-9d8e-65730c0d198c.png">

Did you come across similar errors?

**Comment by davidmartos96** [comment]
I can't test it in an iOS device at the moment, but now that I look at it, it looks like the base `sqflite` repo does not have a Podfile in the ios folder of the example project.
To use SqlCipher it is required to add the dependency to the Podfile as in the README
![image](https://user-images.githubusercontent.com/22084723/69347911-98a6da00-0c75-11ea-9d81-42e83ca1510e.png)
I would start by trying out that yourself if a Podfile was generated for you. I will take a look at it myself later though. 

This is a screenshot of the Podfile in my Flutter project for reference
![image](https://user-images.githubusercontent.com/22084723/69348146-fc310780-0c75-11ea-9444-055e774d8f6c.png)


Thanks for reporting.

**Comment by hellowtisch** [comment]
I did have the pod-file with your addition, when the error occured.

**Comment by hellowtisch** [comment]
it seemed that in the original Sqflite package the iOS example was outdated. David has updated it today, and it is working again.
How can I merge his changes into your package? Could you give me a hint?


Thanks

**Comment by davidmartos96** [comment]
Alright, I have just merged the changes from sqflite into this repo. Pull the latest changes and see if the example runs for you now on iOS.

**Comment by hellowtisch** [comment]
yes, it's working now! Thank you
