### ISSUE TITLE
Update Sqflite to the lastest version

### ISSUE THREAD

**Issue by KristijanZic** [davidmartos96/sqflite_sqlcipher#73]
This lib seems to be behind the Sqflite for a long time. Could you sync it with the latest Sqflite?

**Comment by davidmartos96** [comment]
I'm currently quite busy to dedicate time to that, considering sqflite versions change almost nothing and have been very stable over the years.
I'm happy to accept PRs though.

**Comment by KristijanZic** [comment]
No worries, I understand. No big deal while it works then.

**Comment by davidmartos96** [comment]
This package uses `sqflite_common` under the hood, which can use latest version. Even though this repo started as a fork, it doesn't necessarily need to match what you see in the `sqflite` repository.
