### ISSUE TITLE
Hai, I have built the SQLCipher source in Windows. But please let me know how to encrypt an already existing database using it. 

### ISSUE THREAD

**Issue by Shruthi125** [davidmartos96/sqflite_sqlcipher#75]

**Comment by davidmartos96** [comment]
This script encrypts a database passed by parameter
https://github.com/davidmartos96/sqflite_sqlcipher/issues/74#issuecomment-1639483647

Then it copies it to the assets folder in your app

**Comment by davidmartos96** [comment]
@Shruthi125  to confirm that you correctly installed SQLCipher on your Windows you can do the following.

Open a cmd and then do the following

```sh
> sqlcipher
> PRAGMA cipher_version();
```
It should output something along the lines of SQLCipher Community Version 4.x

**Comment by Shruthi125** [comment]
Yes, I got that---  sqlite> PRAGMA cipher_version;
                            4.5.4 community.
 What are the commands to be run on the prompt  to encrypt an already created db?

**Comment by davidmartos96** [comment]
@Shruthi125 Here https://github.com/davidmartos96/sqflite_sqlcipher/issues/74#issuecomment-1639483647

**Comment by Shruthi125** [comment]
> This script encrypts a database passed by parameter [#74 (comment)](https://github.com/davidmartos96/sqflite_sqlcipher/issues/74#issuecomment-1639483647)
> 
> Then it copies it to the assets folder in your app

Please let me know prompt run commands other than git bash scripts

**Comment by davidmartos96** [comment]
@Shruthi125 While inside a SQLCipher session with the regular sqlite database opened, you can run this.

ATTACH DATABASE 'encrypted.db' AS encrypted KEY '123456ABC'; SELECT sqlcipher_export('encrypted'); DETACH DATABASE encrypted;

It will create a new file named encrypted.db

**Comment by Shruthi125** [comment]
Ohk. Thank you! Let me check if its working.

**Comment by Shruthi125** [comment]
> @Shruthi125 to confirm that you correctly installed SQLCipher on your Windows you can do the following.
> 
> Open a cmd and then do the following
> 
> ```shell
> > sqlcipher  # This would be the executable that you compiled. Maybe it's called simply sqlite when building, I'm not 100% sure
> > PRAGMA cipher_version();
> ```
> 
> It should output something along the lines of SQLCipher Community Version 4.x

The .exe file that got installed is sqlite3.   Is there any other exe file to be built?

**Comment by davidmartos96** [comment]
@Shruthi125 I don't think so. You could rename it to sqlcipher.exe or leave it as is. Sqlcipher is an extension on top of regular Sqlite, you can use it like a regular Sqlite by not providing a password.

**Comment by davidmartos96** [comment]
Closing, as this is not exactly an issue. You can open a discussion instead.
