### ISSUE TITLE
how to use encryption？

### ISSUE THREAD

**Issue by programmerElephant** [davidmartos96/sqflite_sqlcipher#8]
Hi, david.it's not clear to me how to use encryption?
1.when i create a database.there is no place to set password.
2.
    if (await Directory(dirname(path)).exists()) {
      /// why delete it ?
      await deleteDatabase(path);
    }
```

i hope get your response. thank you

**Comment by davidmartos96** [comment]
HI, I imagine you are referring to the example project. The db is deleted at the start as a cleanup for the test itself. 
I don't really understand your point 1 though. Could you specify a bit more?

**Comment by programmerElephant** [comment]
Thank you for your reply. I didn't understand it just now. Now I have understood it

**Comment by davidmartos96** [comment]
Great!
