### ISSUE TITLE
sqlite中现在的加密方式如下：SQLCipher: AES 256 bit;System.Data.Sqlite:RC4; sqleet:ChaCha20-Poly1305;wxSQLite3: AES 128 Bit;wxSQLite3: AEX 256 Bit;以上加密方式有能用此插件解密的吗？期待你的答复，非常感谢！

### ISSUE THREAD

**Issue by jxl-hash** [davidmartos96/sqflite_sqlcipher#81]

**Comment by davidmartos96** [comment]
As stated in your previous post, only SQLCipher encryption implementation is supported.

Please, try to post in English so that more people in the platform can understand what is being asked/discussed.

**Comment by jxl-hash** [comment]
Ok, thank you very much for your reply. I will try my best to use English in the future, thank you
