### ISSUE TITLE
page size?

### ISSUE THREAD

**Issue by ramsestom** [davidmartos96/sqflite_sqlcipher#9]
what is the default page size used by the cypher? I tried to open one of my encrypted database created from a flutter app using this lib (so as the example_pass_1234.db from the example folder) with `DB browser for SQLite` but couldn't find the correct page size (tested with a value of 4096, 2048, 1024, 512, 256, 128 but none of these worked)

**Comment by davidmartos96** [comment]
That database is created with SqlCipher 4 and its default pass parameters. From my understanding you need to have sqlite browser compiled with version 4  of SqlCipher in order to open it. I can open that sample db fine with my sqlite browser.

**Comment by davidmartos96** [comment]
@ramsestom These are the encryption settings for that sample asset database with password "1234"
![image](https://user-images.githubusercontent.com/22084723/71975914-69dcc700-3215-11ea-8eaa-9d50270c61d6.png)
If your db was created within the app you should be able to open it with the defaults.

**Comment by ramsestom** [comment]
Thanks. updated my version of DB browser for SQLite to the latest and it worked (don't know why the previous version, from just 4 to 6 months ago, failed to open the database with the correct parametters...)
