### ISSUE TITLE
The lower bound of "sdk: '>=2.4.0-dev <3.0.0'" must be 2.12.0 or higher to enable null safety.

### ISSUE THREAD

**Issue by chunsfire** [davidmartos96/sqflite_sqlcipher#93]
Getting below error;

```
The current Dart SDK version is 3.4.0.

Because firstapp depends on sqflite_sqlcipher_repo from git which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.4.0-dev <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
```

**Comment by davidmartos96** [comment]
@chunsfire It looks like you are depending on the package with a git dependency.
Could you post how your pubspec.yaml looks like?
Note that the root pubspec.yaml in the repo is not the one you are looking for, but the one inside the folder sqflite.

**Comment by chunsfire** [comment]
name: firstapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screen_lock:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/flutter_screen_lock  
  #http: ^1.2.1
  animated_splash_screen:
    git: 
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/animated_splash_screen
  sqlite3_flutter_libs:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqlite3_flutter_libs      
  sqflite:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqflite    
  sqflite_sqlcipher_repo:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqflite_sqlcipher  
     
  # firebase_messaging: ^14.9.2
  # firebase_core: ^2.31.0
  # flutter_local_notifications: ^17.1.2
  # path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

**Comment by chunsfire** [comment]
`name: firstapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screen_lock:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/flutter_screen_lock  
  #http: ^1.2.1
  animated_splash_screen:
    git: 
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/animated_splash_screen
  sqlite3_flutter_libs:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqlite3_flutter_libs      
  sqflite:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqflite    
  sqflite_sqlcipher_repo:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqflite_sqlcipher  
     
  # firebase_messaging: ^14.9.2
  # firebase_core: ^2.31.0
  # flutter_local_notifications: ^17.1.2
  # path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
`

**Comment by chunsfire** [comment]
[pubspec.json](https://github.com/davidmartos96/sqflite_sqlcipher/files/15389416/pubspec.json)

**Comment by chunsfire** [comment]
[pubspec.txt](https://github.com/davidmartos96/sqflite_sqlcipher/files/15389436/pubspec.txt)

**Comment by davidmartos96** [comment]
@chunsfire  The path you are using in the git dependency is the problem.

If you have your own reasons for not using pub.dev versioning, note that the way you have it will be pulling latest master on each of your dependencies, which can break unexpectedly. You can add `ref: <some commit hash/branch name/tag>` you are interested in.
But managing your dependencies via pub would be definitely easier.

With git dependencies try the following. It should fix the other issue you opened too.

```yaml
sqflite_sqlcipher:
    git:
      url: git@testhost:fmw-idm-cloud/flutter-packages.git
      path: packages/sqflite_sqlcipher/sqflite
      ref: v3.1.0
```

**Comment by chunsfire** [comment]
thanks for suggesting the fix.
If I am giving "ref", its throwing an error;
`Because firstapp depends on sqflite_sqlcipher from git which doesn't exist (Could not find git ref 'v3.1.0' (fatal: ambiguous argument 'v3.1.0': unknown revision or path not in the working tree.`

While w/o that it's able to resolve the dependency correctly. And yes the version is now coming correctly.

**Comment by davidmartos96** [comment]
@chunsfire That's because the git url you are using is not pointing to this repository.
You could use this url instead
 https://github.com/davidmartos96/sqflite_sqlcipher
