### ISSUE TITLE
DatabaseException(Error Domain=FMDatabase Code=26 "file is not a database" UserInfo={NSLocalizedDescription=file is not a database}) sql 'BEGIN EXCLUSIVE' args []

### ISSUE THREAD

**Issue by amrLLSE** [davidmartos96/sqflite_sqlcipher#98]
I'm facing this issue on the latest sqflite_sqlcipher plugin

SqfliteDatabaseException factory_sql_cipher_impl.dart in SqfliteSqlCipherDatabaseFactoryImpl.wrapDatabaseException

DatabaseException(Error Domain=FMDatabase Code=26 "file is not a database" UserInfo={NSLocalizedDescription=file is not a database}) sql 'BEGIN EXCLUSIVE' args []

**Comment by davidmartos96** [comment]
Closing, as the reason for the error should be the same from #99 
@amrLLSE  Did you get any chance to try the recommendations from the other issue?

**Comment by amrLLSE** [comment]
@davidmartos96 Unfortunately no, but still investigating and will let you know on #99.
